# Generated by Django 6.0.5 on 2026-05-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('member', 'Membro'), ('junior', 'Júnior')], default='member', max_length=10),
        ),
    ]
