# Generated by Django 6.0.4 on 2026-05-19 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('icone', models.ImageField(blank=True, null=True, upload_to='categorias/')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('unidade', models.CharField(choices=[('un', 'Unidade'), ('cx', 'Caixa'), ('kg', 'Quilograma'), ('g', 'Grama'), ('L', 'Litro'), ('mL', 'Mililitro')], default='un', max_length=20)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='products.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDispensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unidade', models.CharField(blank=True, max_length=20)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('congelado', models.BooleanField(default=False)),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
                ('adicionado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_dispensa', to='family.familia')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_dispensa', to='products.produto')),
            ],
        ),
    ]
