# Generated by Django 6.0.4 on 2026-05-21 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='unidade',
        ),
    ]
