# Generated by Django 6.0.4 on 2026-05-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_produto_codigo_barras_produto_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='unidade',
            field=models.CharField(choices=[('un', 'Unidade'), ('cx', 'Caixa'), ('kg', 'Quilograma'), ('g', 'Grama'), ('L', 'Litro'), ('mL', 'Mililitro')], default='un', max_length=20),
        ),
    ]
