# Generated by Django 6.0.4 on 2026-05-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_produto_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdispensa',
            name='congelado',
            field=models.BooleanField(default=False),
        ),
    ]
