# Generated by Django 6.0.4 on 2026-05-19 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='membrofamilia',
            old_name='family_id',
            new_name='family',
        ),
        migrations.RemoveField(
            model_name='membrofamilia',
            name='userid',
        ),
        migrations.AddField(
            model_name='membrofamilia',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
