# Generated by Django 6.0.5 on 2026-05-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrofamilia',
            name='papel',
            field=models.CharField(choices=[('admin', 'Administrador'), ('member', 'Membro'), ('junior', 'Júnior')], default='member', max_length=20),
        ),
    ]
