# Generated by Django 6.0.4 on 2026-05-11 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membrofamilia',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='membrofamilia',
            name='nome',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membrofamilia',
            name='papel',
            field=models.CharField(choices=[('junior', 'Junior'), ('membro', 'Membro'), ('administrador', 'Administrador')], default='membro', max_length=20),
        ),
        migrations.AlterField(
            model_name='membrofamilia',
            name='utilizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='familias', to=settings.AUTH_USER_MODEL),
        ),
    ]
