# Generated by Django 6.0.5 on 2026-05-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlistacompra',
            name='categoria',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='itemlistacompra',
            name='icone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='itemlistacompra',
            name='nome_livre',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='itempedidocompra',
            name='icone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='itempedidocompra',
            name='nome_livre',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
