# Generated by Django 6.0.4 on 2026-05-11 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_alter_membrofamilia_unique_together_and_more'),
        ('products', '0002_remove_produto_codigo_barras_produto_quantidade_and_more'),
        ('shopping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listacompras',
            name='criada_por',
        ),
        migrations.RemoveField(
            model_name='listacompras',
            name='familia',
        ),
        migrations.CreateModel(
            name='ItemListaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('unidade', models.CharField(blank=True, max_length=20)),
                ('adicionado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_compras', to='family.familia')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.produto')),
            ],
        ),
        migrations.DeleteModel(
            name='ItemListaCompras',
        ),
        migrations.DeleteModel(
            name='ListaCompras',
        ),
    ]
