# Generated by Django 6.0.4 on 2026-05-11 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_produto_unidade'),
        ('shopping', '0003_pedidocompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidocompra',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='pedidocompra',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='pedidocompra',
            name='unidade',
        ),
        migrations.CreateModel(
            name='ItemPedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='shopping.pedidocompra')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.produto')),
            ],
        ),
    ]
