# Generated by Django 6.0.4 on 2026-05-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_remove_pedidocompra_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlistacompra',
            name='categoria',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='itemlistacompra',
            name='icone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='itemlistacompra',
            name='nome_livre',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
