# Generated by Django 6.0.4 on 2026-05-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_add_nome_livre_icone_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedidocompra',
            name='icone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='itempedidocompra',
            name='nome_livre',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
