# Generated by Django 6.0.4 on 2026-05-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitasugerida',
            name='passos',
            field=models.JSONField(default=list),
        ),
    ]
