# Generated by Django 6.0.4 on 2026-05-11 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_produto_codigo_barras_produto_quantidade_and_more'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receitasugerida',
            name='imagem_url',
        ),
        migrations.AddField(
            model_name='receitasugerida',
            name='produto_imagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas_como_imagem', to='products.produto'),
        ),
    ]
